# Generated by Django 3.1.1 on 2020-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_auto_20201130_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='distancia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='elevacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nivel_dificultad',
            field=models.CharField(choices=[('EASY', 'easy'), ('MODERATE', 'moderate'), ('HIGH', 'high'), ('CHALLENGING', 'challenging')], default='EASY', max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='F', max_length=1),
        ),
    ]
