# Generated by Django 3.1.3 on 2020-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_post_id_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('EASY', 'easy'), ('MODERATE', 'moderate'), ('HIGH', 'high'), ('CHALLENGING', 'challenging')], default='EASY', max_length=11),
        ),
    ]
