# Generated by Django 3.1.3 on 2020-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_auto_20201203_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('EASY', 'easy'), ('MODERATE', 'moderate'), ('HIGH', 'high'), ('CHALLENGING', 'challenging')], default='EASY', max_length=11),
        ),
    ]
