# Generated by Django 3.1.1 on 2020-11-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_auto_20201124_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='id_etapa',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rutas.etapa'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='id_pais',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rutas.pais'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='id_usuario',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rutas.usuario'),
        ),
    ]
