# Generated by Django 3.1.1 on 2020-11-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_auto_20201125_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='id_etapa',
        ),
    ]
