# Generated by Django 3.1.1 on 2020-11-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_auto_20201128_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='codigo_pais',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relacionamentousuarioruta',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rutas.usuario'),
            preserve_default=False,
        ),
    ]
