# Generated by Django 3.1.1 on 2020-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_auto_20201128_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(default='', max_length=50),
        ),
    ]
