# Generated by Django 3.1.3 on 2020-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_auto_20201130_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='numero_etapa',
            field=models.IntegerField(default=0),
        ),
    ]
