# Generated by Django 3.1.1 on 2020-12-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_auto_20201205_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelacionamentoUsuarioRuta',
        ),
    ]
