# Generated by Django 3.1.1 on 2020-12-06 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rutas', '0011_delete_relacionamentousuarioruta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Comentario',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='creation_date',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='title',
            new_name='titulo',
        ),
    ]
